title: "Dinesh Devanaboina Portfolio"
description: "Full Stack Developer | Java | MERN"
image: "https://raw.githubusercontent.com/Dineshdevanaboina/portfolio/main/Dinesh.jpg"
#show_downloads: true
theme: jekyll-theme-minimal
